# Generated by Django 5.2.1 on 2025-07-03 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short title for the task', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the task', null=True)),
                ('complete', models.BooleanField(default=False, help_text='Whether the task is completed')),
                ('due_date', models.DateTimeField(blank=True, help_text='When the task is due', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When the task was created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='When the task was last updated')),
                ('user', models.ForeignKey(help_text='The user who owns this task', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['complete', '-created'],
            },
        ),
    ]
